# Generated by Django 4.2.1 on 2023-05-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register_email',
            new_name='Registered_email',
        ),
    ]
